/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddTipInput { 'tipAmountUSD' : bigint, 'jobId' : JobId }
export interface CreateEnterpriseDispatchInput {
  'title' : string,
  'serviceCategory' : ServiceCategory,
  'description' : string,
  'address' : string,
  'budgetUSD' : bigint,
}
export interface CreateJobInput {
  'latitude' : number,
  'photoRefs' : Array<string>,
  'title' : string,
  'serviceCategory' : ServiceCategory,
  'description' : string,
  'longitude' : number,
  'address' : string,
  'budgetUSD' : bigint,
}
export type EnterpriseDispatchId = bigint;
export interface EnterpriseDispatchPublic {
  'id' : EnterpriseDispatchId,
  'status' : EnterpriseDispatchStatus,
  'title' : string,
  'serviceCategory' : ServiceCategory,
  'createdAt' : Timestamp,
  'description' : string,
  'enterpriseClientId' : UserId,
  'updatedAt' : Timestamp,
  'workerIds' : Array<UserId>,
  'address' : string,
  'budgetUSD' : bigint,
}
export type EnterpriseDispatchStatus = { 'Open' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type EscrowStatus = { 'Refunded' : null } |
  { 'Held' : null } |
  { 'Released' : null };
export interface HomeownerProfilePublic {
  'latitude' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'averageRating' : number,
  'longitude' : number,
  'address' : string,
}
export interface InitiatePaymentInput {
  'jobId' : JobId,
  'stripePaymentIntentId' : string,
  'amountUSD' : bigint,
}
export type JobId = bigint;
export interface JobPublic {
  'id' : JobId,
  'status' : JobStatus,
  'latitude' : number,
  'completedAt' : [] | [Timestamp],
  'photoRefs' : Array<string>,
  'title' : string,
  'serviceCategory' : ServiceCategory,
  'workerId' : [] | [UserId],
  'workerConfirmed' : boolean,
  'tipAmountUSD' : [] | [bigint],
  'createdAt' : Timestamp,
  'homeownerId' : UserId,
  'description' : string,
  'longitude' : number,
  'address' : string,
  'budgetUSD' : bigint,
  'acceptedAt' : [] | [Timestamp],
  'homeownerConfirmed' : boolean,
}
export type JobStatus = { 'Disputed' : null } |
  { 'Open' : null } |
  { 'Accepted' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type NotificationId = bigint;
export interface NotificationPublic {
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'jobId' : [] | [JobId],
  'isRead' : boolean,
  'message' : string,
}
export type NotificationType = { 'JobAccepted' : null } |
  { 'EnterpriseDispatch' : null } |
  { 'TipReceived' : null } |
  { 'JobCompleted' : null } |
  { 'JobAvailable' : null } |
  { 'RatingReceived' : null };
export type PaymentId = bigint;
export interface PaymentRecordPublic {
  'id' : PaymentId,
  'tipAmountUSD' : bigint,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'escrowStatus' : EscrowStatus,
  'updatedAt' : Timestamp,
  'commissionAmount' : bigint,
  'stripePaymentIntentId' : string,
  'amountUSD' : bigint,
  'stripePayoutId' : [] | [string],
}
export interface Rating {
  'id' : RatingId,
  'ratedUserId' : UserId,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'score' : bigint,
  'ratedByUserId' : UserId,
  'comment' : [] | [string],
}
export type RatingId = bigint;
export interface RegisterHomeownerInput {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export interface RegisterWorkerInput {
  'latitude' : number,
  'idDocRef' : [] | [string],
  'serviceCategories' : Array<ServiceCategory>,
  'longitude' : number,
  'insuranceDocRef' : [] | [string],
}
export type ServiceCategory = { 'BushTrimming' : null } |
  { 'GeneralYardWork' : null } |
  { 'LeafRaking' : null } |
  { 'LawnMowing' : null } |
  { 'WindowWashing' : null } |
  { 'WeedWhacking' : null } |
  { 'SnowPlowing' : null } |
  { 'GutterCleaning' : null } |
  { 'PressureWashing' : null };
export interface SubmitRatingInput {
  'ratedUserId' : UserId,
  'jobId' : JobId,
  'score' : bigint,
  'comment' : [] | [string],
}
export type Timestamp = bigint;
export type UserId = Principal;
export type VerificationStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface WorkerProfilePublic {
  'latitude' : number,
  'enterpriseTier' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'serviceCategories' : Array<ServiceCategory>,
  'averageRating' : number,
  'longitude' : number,
  'radiusMiles' : bigint,
  'completedJobsCount' : bigint,
  'verificationStatus' : VerificationStatus,
}
export interface _SERVICE {
  'acceptJob' : ActorMethod<[JobId], boolean>,
  'acceptLiabilityWaiver' : ActorMethod<[string], boolean>,
  'addJobTip' : ActorMethod<[JobId, bigint], boolean>,
  'addTip' : ActorMethod<[AddTipInput], boolean>,
  'assignWorkerToDispatch' : ActorMethod<
    [EnterpriseDispatchId, UserId],
    boolean
  >,
  'cancelJob' : ActorMethod<[JobId], boolean>,
  'createEnterpriseDispatch' : ActorMethod<
    [CreateEnterpriseDispatchInput],
    EnterpriseDispatchPublic
  >,
  'createJob' : ActorMethod<[CreateJobInput], JobPublic>,
  'disputeJob' : ActorMethod<[JobId], boolean>,
  'findNearbyWorkers' : ActorMethod<
    [number, number, ServiceCategory],
    Array<WorkerProfilePublic>
  >,
  'getAvailableJobs' : ActorMethod<[], Array<JobPublic>>,
  'getAverageRating' : ActorMethod<[UserId], number>,
  'getEnterpriseDispatch' : ActorMethod<
    [EnterpriseDispatchId],
    [] | [EnterpriseDispatchPublic]
  >,
  'getHomeownerProfile' : ActorMethod<[UserId], [] | [HomeownerProfilePublic]>,
  'getJob' : ActorMethod<[JobId], [] | [JobPublic]>,
  'getMyEnterpriseDispatches' : ActorMethod<
    [],
    Array<EnterpriseDispatchPublic>
  >,
  'getMyHomeownerProfile' : ActorMethod<[], [] | [HomeownerProfilePublic]>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  'getMyPostedJobs' : ActorMethod<[], Array<JobPublic>>,
  'getMyWorkerJobs' : ActorMethod<[], Array<JobPublic>>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfilePublic]>,
  'getOpenEnterpriseDispatches' : ActorMethod<
    [],
    Array<EnterpriseDispatchPublic>
  >,
  'getPaymentForJob' : ActorMethod<[JobId], [] | [PaymentRecordPublic]>,
  'getRatingsForUser' : ActorMethod<[UserId], Array<Rating>>,
  'getWorkerProfile' : ActorMethod<[UserId], [] | [WorkerProfilePublic]>,
  'hasAcceptedWaiver' : ActorMethod<[], boolean>,
  'homeownerConfirmCompletion' : ActorMethod<[JobId], boolean>,
  'initiateEscrow' : ActorMethod<[InitiatePaymentInput], PaymentRecordPublic>,
  'markAllNotificationsRead' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'refundEscrow' : ActorMethod<[JobId], boolean>,
  'registerHomeowner' : ActorMethod<
    [RegisterHomeownerInput],
    HomeownerProfilePublic
  >,
  'registerWorker' : ActorMethod<[RegisterWorkerInput], WorkerProfilePublic>,
  'releaseEscrow' : ActorMethod<[JobId, string], boolean>,
  'removeWorkerFromDispatch' : ActorMethod<
    [EnterpriseDispatchId, UserId],
    boolean
  >,
  'startJob' : ActorMethod<[JobId], boolean>,
  'submitRating' : ActorMethod<[SubmitRatingInput], Rating>,
  'updateEnterpriseDispatchStatus' : ActorMethod<
    [EnterpriseDispatchId, EnterpriseDispatchStatus],
    boolean
  >,
  'updateWorkerLocation' : ActorMethod<[number, number], boolean>,
  'updateWorkerRadius' : ActorMethod<[bigint], boolean>,
  'updateWorkerVerification' : ActorMethod<
    [UserId, VerificationStatus],
    boolean
  >,
  'workerConfirmCompletion' : ActorMethod<[JobId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];