/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobId = IDL.Nat;
export const AddTipInput = IDL.Record({
  'tipAmountUSD' : IDL.Nat,
  'jobId' : JobId,
});
export const EnterpriseDispatchId = IDL.Nat;
export const UserId = IDL.Principal;
export const ServiceCategory = IDL.Variant({
  'BushTrimming' : IDL.Null,
  'GeneralYardWork' : IDL.Null,
  'LeafRaking' : IDL.Null,
  'LawnMowing' : IDL.Null,
  'WindowWashing' : IDL.Null,
  'WeedWhacking' : IDL.Null,
  'SnowPlowing' : IDL.Null,
  'GutterCleaning' : IDL.Null,
  'PressureWashing' : IDL.Null,
});
export const CreateEnterpriseDispatchInput = IDL.Record({
  'title' : IDL.Text,
  'serviceCategory' : ServiceCategory,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'budgetUSD' : IDL.Nat,
});
export const EnterpriseDispatchStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const EnterpriseDispatchPublic = IDL.Record({
  'id' : EnterpriseDispatchId,
  'status' : EnterpriseDispatchStatus,
  'title' : IDL.Text,
  'serviceCategory' : ServiceCategory,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'enterpriseClientId' : UserId,
  'updatedAt' : Timestamp,
  'workerIds' : IDL.Vec(UserId),
  'address' : IDL.Text,
  'budgetUSD' : IDL.Nat,
});
export const CreateJobInput = IDL.Record({
  'latitude' : IDL.Float64,
  'photoRefs' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'serviceCategory' : ServiceCategory,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'budgetUSD' : IDL.Nat,
});
export const JobStatus = IDL.Variant({
  'Disputed' : IDL.Null,
  'Open' : IDL.Null,
  'Accepted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const JobPublic = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'latitude' : IDL.Float64,
  'completedAt' : IDL.Opt(Timestamp),
  'photoRefs' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'serviceCategory' : ServiceCategory,
  'workerId' : IDL.Opt(UserId),
  'workerConfirmed' : IDL.Bool,
  'tipAmountUSD' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'homeownerId' : UserId,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'budgetUSD' : IDL.Nat,
  'acceptedAt' : IDL.Opt(Timestamp),
  'homeownerConfirmed' : IDL.Bool,
});
export const VerificationStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WorkerProfilePublic = IDL.Record({
  'latitude' : IDL.Float64,
  'enterpriseTier' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'serviceCategories' : IDL.Vec(ServiceCategory),
  'averageRating' : IDL.Float64,
  'longitude' : IDL.Float64,
  'radiusMiles' : IDL.Nat,
  'completedJobsCount' : IDL.Nat,
  'verificationStatus' : VerificationStatus,
});
export const HomeownerProfilePublic = IDL.Record({
  'latitude' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'averageRating' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'JobAccepted' : IDL.Null,
  'EnterpriseDispatch' : IDL.Null,
  'TipReceived' : IDL.Null,
  'JobCompleted' : IDL.Null,
  'JobAvailable' : IDL.Null,
  'RatingReceived' : IDL.Null,
});
export const NotificationPublic = IDL.Record({
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'jobId' : IDL.Opt(JobId),
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const PaymentId = IDL.Nat;
export const EscrowStatus = IDL.Variant({
  'Refunded' : IDL.Null,
  'Held' : IDL.Null,
  'Released' : IDL.Null,
});
export const PaymentRecordPublic = IDL.Record({
  'id' : PaymentId,
  'tipAmountUSD' : IDL.Nat,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'escrowStatus' : EscrowStatus,
  'updatedAt' : Timestamp,
  'commissionAmount' : IDL.Nat,
  'stripePaymentIntentId' : IDL.Text,
  'amountUSD' : IDL.Nat,
  'stripePayoutId' : IDL.Opt(IDL.Text),
});
export const RatingId = IDL.Nat;
export const Rating = IDL.Record({
  'id' : RatingId,
  'ratedUserId' : UserId,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'score' : IDL.Nat,
  'ratedByUserId' : UserId,
  'comment' : IDL.Opt(IDL.Text),
});
export const InitiatePaymentInput = IDL.Record({
  'jobId' : JobId,
  'stripePaymentIntentId' : IDL.Text,
  'amountUSD' : IDL.Nat,
});
export const RegisterHomeownerInput = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const RegisterWorkerInput = IDL.Record({
  'latitude' : IDL.Float64,
  'idDocRef' : IDL.Opt(IDL.Text),
  'serviceCategories' : IDL.Vec(ServiceCategory),
  'longitude' : IDL.Float64,
  'insuranceDocRef' : IDL.Opt(IDL.Text),
});
export const SubmitRatingInput = IDL.Record({
  'ratedUserId' : UserId,
  'jobId' : JobId,
  'score' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'acceptJob' : IDL.Func([JobId], [IDL.Bool], []),
  'acceptLiabilityWaiver' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addJobTip' : IDL.Func([JobId, IDL.Nat], [IDL.Bool], []),
  'addTip' : IDL.Func([AddTipInput], [IDL.Bool], []),
  'assignWorkerToDispatch' : IDL.Func(
      [EnterpriseDispatchId, UserId],
      [IDL.Bool],
      [],
    ),
  'cancelJob' : IDL.Func([JobId], [IDL.Bool], []),
  'createEnterpriseDispatch' : IDL.Func(
      [CreateEnterpriseDispatchInput],
      [EnterpriseDispatchPublic],
      [],
    ),
  'createJob' : IDL.Func([CreateJobInput], [JobPublic], []),
  'disputeJob' : IDL.Func([JobId], [IDL.Bool], []),
  'findNearbyWorkers' : IDL.Func(
      [IDL.Float64, IDL.Float64, ServiceCategory],
      [IDL.Vec(WorkerProfilePublic)],
      ['query'],
    ),
  'getAvailableJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
  'getAverageRating' : IDL.Func([UserId], [IDL.Float64], ['query']),
  'getEnterpriseDispatch' : IDL.Func(
      [EnterpriseDispatchId],
      [IDL.Opt(EnterpriseDispatchPublic)],
      ['query'],
    ),
  'getHomeownerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(HomeownerProfilePublic)],
      ['query'],
    ),
  'getJob' : IDL.Func([JobId], [IDL.Opt(JobPublic)], ['query']),
  'getMyEnterpriseDispatches' : IDL.Func(
      [],
      [IDL.Vec(EnterpriseDispatchPublic)],
      ['query'],
    ),
  'getMyHomeownerProfile' : IDL.Func(
      [],
      [IDL.Opt(HomeownerProfilePublic)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
  'getMyPostedJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
  'getMyWorkerJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
  'getMyWorkerProfile' : IDL.Func(
      [],
      [IDL.Opt(WorkerProfilePublic)],
      ['query'],
    ),
  'getOpenEnterpriseDispatches' : IDL.Func(
      [],
      [IDL.Vec(EnterpriseDispatchPublic)],
      ['query'],
    ),
  'getPaymentForJob' : IDL.Func(
      [JobId],
      [IDL.Opt(PaymentRecordPublic)],
      ['query'],
    ),
  'getRatingsForUser' : IDL.Func([UserId], [IDL.Vec(Rating)], ['query']),
  'getWorkerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(WorkerProfilePublic)],
      ['query'],
    ),
  'hasAcceptedWaiver' : IDL.Func([], [IDL.Bool], ['query']),
  'homeownerConfirmCompletion' : IDL.Func([JobId], [IDL.Bool], []),
  'initiateEscrow' : IDL.Func(
      [InitiatePaymentInput],
      [PaymentRecordPublic],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'refundEscrow' : IDL.Func([JobId], [IDL.Bool], []),
  'registerHomeowner' : IDL.Func(
      [RegisterHomeownerInput],
      [HomeownerProfilePublic],
      [],
    ),
  'registerWorker' : IDL.Func([RegisterWorkerInput], [WorkerProfilePublic], []),
  'releaseEscrow' : IDL.Func([JobId, IDL.Text], [IDL.Bool], []),
  'removeWorkerFromDispatch' : IDL.Func(
      [EnterpriseDispatchId, UserId],
      [IDL.Bool],
      [],
    ),
  'startJob' : IDL.Func([JobId], [IDL.Bool], []),
  'submitRating' : IDL.Func([SubmitRatingInput], [Rating], []),
  'updateEnterpriseDispatchStatus' : IDL.Func(
      [EnterpriseDispatchId, EnterpriseDispatchStatus],
      [IDL.Bool],
      [],
    ),
  'updateWorkerLocation' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Bool], []),
  'updateWorkerRadius' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateWorkerVerification' : IDL.Func(
      [UserId, VerificationStatus],
      [IDL.Bool],
      [],
    ),
  'workerConfirmCompletion' : IDL.Func([JobId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobId = IDL.Nat;
  const AddTipInput = IDL.Record({ 'tipAmountUSD' : IDL.Nat, 'jobId' : JobId });
  const EnterpriseDispatchId = IDL.Nat;
  const UserId = IDL.Principal;
  const ServiceCategory = IDL.Variant({
    'BushTrimming' : IDL.Null,
    'GeneralYardWork' : IDL.Null,
    'LeafRaking' : IDL.Null,
    'LawnMowing' : IDL.Null,
    'WindowWashing' : IDL.Null,
    'WeedWhacking' : IDL.Null,
    'SnowPlowing' : IDL.Null,
    'GutterCleaning' : IDL.Null,
    'PressureWashing' : IDL.Null,
  });
  const CreateEnterpriseDispatchInput = IDL.Record({
    'title' : IDL.Text,
    'serviceCategory' : ServiceCategory,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'budgetUSD' : IDL.Nat,
  });
  const EnterpriseDispatchStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const EnterpriseDispatchPublic = IDL.Record({
    'id' : EnterpriseDispatchId,
    'status' : EnterpriseDispatchStatus,
    'title' : IDL.Text,
    'serviceCategory' : ServiceCategory,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'enterpriseClientId' : UserId,
    'updatedAt' : Timestamp,
    'workerIds' : IDL.Vec(UserId),
    'address' : IDL.Text,
    'budgetUSD' : IDL.Nat,
  });
  const CreateJobInput = IDL.Record({
    'latitude' : IDL.Float64,
    'photoRefs' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'serviceCategory' : ServiceCategory,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'budgetUSD' : IDL.Nat,
  });
  const JobStatus = IDL.Variant({
    'Disputed' : IDL.Null,
    'Open' : IDL.Null,
    'Accepted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const JobPublic = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'latitude' : IDL.Float64,
    'completedAt' : IDL.Opt(Timestamp),
    'photoRefs' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'serviceCategory' : ServiceCategory,
    'workerId' : IDL.Opt(UserId),
    'workerConfirmed' : IDL.Bool,
    'tipAmountUSD' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'homeownerId' : UserId,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'budgetUSD' : IDL.Nat,
    'acceptedAt' : IDL.Opt(Timestamp),
    'homeownerConfirmed' : IDL.Bool,
  });
  const VerificationStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WorkerProfilePublic = IDL.Record({
    'latitude' : IDL.Float64,
    'enterpriseTier' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'serviceCategories' : IDL.Vec(ServiceCategory),
    'averageRating' : IDL.Float64,
    'longitude' : IDL.Float64,
    'radiusMiles' : IDL.Nat,
    'completedJobsCount' : IDL.Nat,
    'verificationStatus' : VerificationStatus,
  });
  const HomeownerProfilePublic = IDL.Record({
    'latitude' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'averageRating' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'JobAccepted' : IDL.Null,
    'EnterpriseDispatch' : IDL.Null,
    'TipReceived' : IDL.Null,
    'JobCompleted' : IDL.Null,
    'JobAvailable' : IDL.Null,
    'RatingReceived' : IDL.Null,
  });
  const NotificationPublic = IDL.Record({
    'id' : NotificationId,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'jobId' : IDL.Opt(JobId),
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const PaymentId = IDL.Nat;
  const EscrowStatus = IDL.Variant({
    'Refunded' : IDL.Null,
    'Held' : IDL.Null,
    'Released' : IDL.Null,
  });
  const PaymentRecordPublic = IDL.Record({
    'id' : PaymentId,
    'tipAmountUSD' : IDL.Nat,
    'createdAt' : Timestamp,
    'jobId' : JobId,
    'escrowStatus' : EscrowStatus,
    'updatedAt' : Timestamp,
    'commissionAmount' : IDL.Nat,
    'stripePaymentIntentId' : IDL.Text,
    'amountUSD' : IDL.Nat,
    'stripePayoutId' : IDL.Opt(IDL.Text),
  });
  const RatingId = IDL.Nat;
  const Rating = IDL.Record({
    'id' : RatingId,
    'ratedUserId' : UserId,
    'createdAt' : Timestamp,
    'jobId' : JobId,
    'score' : IDL.Nat,
    'ratedByUserId' : UserId,
    'comment' : IDL.Opt(IDL.Text),
  });
  const InitiatePaymentInput = IDL.Record({
    'jobId' : JobId,
    'stripePaymentIntentId' : IDL.Text,
    'amountUSD' : IDL.Nat,
  });
  const RegisterHomeownerInput = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const RegisterWorkerInput = IDL.Record({
    'latitude' : IDL.Float64,
    'idDocRef' : IDL.Opt(IDL.Text),
    'serviceCategories' : IDL.Vec(ServiceCategory),
    'longitude' : IDL.Float64,
    'insuranceDocRef' : IDL.Opt(IDL.Text),
  });
  const SubmitRatingInput = IDL.Record({
    'ratedUserId' : UserId,
    'jobId' : JobId,
    'score' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'acceptJob' : IDL.Func([JobId], [IDL.Bool], []),
    'acceptLiabilityWaiver' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addJobTip' : IDL.Func([JobId, IDL.Nat], [IDL.Bool], []),
    'addTip' : IDL.Func([AddTipInput], [IDL.Bool], []),
    'assignWorkerToDispatch' : IDL.Func(
        [EnterpriseDispatchId, UserId],
        [IDL.Bool],
        [],
      ),
    'cancelJob' : IDL.Func([JobId], [IDL.Bool], []),
    'createEnterpriseDispatch' : IDL.Func(
        [CreateEnterpriseDispatchInput],
        [EnterpriseDispatchPublic],
        [],
      ),
    'createJob' : IDL.Func([CreateJobInput], [JobPublic], []),
    'disputeJob' : IDL.Func([JobId], [IDL.Bool], []),
    'findNearbyWorkers' : IDL.Func(
        [IDL.Float64, IDL.Float64, ServiceCategory],
        [IDL.Vec(WorkerProfilePublic)],
        ['query'],
      ),
    'getAvailableJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
    'getAverageRating' : IDL.Func([UserId], [IDL.Float64], ['query']),
    'getEnterpriseDispatch' : IDL.Func(
        [EnterpriseDispatchId],
        [IDL.Opt(EnterpriseDispatchPublic)],
        ['query'],
      ),
    'getHomeownerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(HomeownerProfilePublic)],
        ['query'],
      ),
    'getJob' : IDL.Func([JobId], [IDL.Opt(JobPublic)], ['query']),
    'getMyEnterpriseDispatches' : IDL.Func(
        [],
        [IDL.Vec(EnterpriseDispatchPublic)],
        ['query'],
      ),
    'getMyHomeownerProfile' : IDL.Func(
        [],
        [IDL.Opt(HomeownerProfilePublic)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getMyPostedJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
    'getMyWorkerJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
    'getMyWorkerProfile' : IDL.Func(
        [],
        [IDL.Opt(WorkerProfilePublic)],
        ['query'],
      ),
    'getOpenEnterpriseDispatches' : IDL.Func(
        [],
        [IDL.Vec(EnterpriseDispatchPublic)],
        ['query'],
      ),
    'getPaymentForJob' : IDL.Func(
        [JobId],
        [IDL.Opt(PaymentRecordPublic)],
        ['query'],
      ),
    'getRatingsForUser' : IDL.Func([UserId], [IDL.Vec(Rating)], ['query']),
    'getWorkerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(WorkerProfilePublic)],
        ['query'],
      ),
    'hasAcceptedWaiver' : IDL.Func([], [IDL.Bool], ['query']),
    'homeownerConfirmCompletion' : IDL.Func([JobId], [IDL.Bool], []),
    'initiateEscrow' : IDL.Func(
        [InitiatePaymentInput],
        [PaymentRecordPublic],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'refundEscrow' : IDL.Func([JobId], [IDL.Bool], []),
    'registerHomeowner' : IDL.Func(
        [RegisterHomeownerInput],
        [HomeownerProfilePublic],
        [],
      ),
    'registerWorker' : IDL.Func(
        [RegisterWorkerInput],
        [WorkerProfilePublic],
        [],
      ),
    'releaseEscrow' : IDL.Func([JobId, IDL.Text], [IDL.Bool], []),
    'removeWorkerFromDispatch' : IDL.Func(
        [EnterpriseDispatchId, UserId],
        [IDL.Bool],
        [],
      ),
    'startJob' : IDL.Func([JobId], [IDL.Bool], []),
    'submitRating' : IDL.Func([SubmitRatingInput], [Rating], []),
    'updateEnterpriseDispatchStatus' : IDL.Func(
        [EnterpriseDispatchId, EnterpriseDispatchStatus],
        [IDL.Bool],
        [],
      ),
    'updateWorkerLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateWorkerRadius' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateWorkerVerification' : IDL.Func(
        [UserId, VerificationStatus],
        [IDL.Bool],
        [],
      ),
    'workerConfirmCompletion' : IDL.Func([JobId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };