/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InitiatePaymentInput {
    jobId: JobId;
    stripePaymentIntentId: string;
    amountUSD: bigint;
}
export type Timestamp = bigint;
export interface Rating {
    id: RatingId;
    ratedUserId: UserId;
    createdAt: Timestamp;
    jobId: JobId;
    score: bigint;
    ratedByUserId: UserId;
    comment?: string;
}
export interface CreateJobInput {
    latitude: number;
    photoRefs: Array<string>;
    title: string;
    serviceCategory: ServiceCategory;
    description: string;
    longitude: number;
    address: string;
    budgetUSD: bigint;
}
export interface AddTipInput {
    tipAmountUSD: bigint;
    jobId: JobId;
}
export interface WorkerProfilePublic {
    latitude: number;
    enterpriseTier: boolean;
    userId: UserId;
    createdAt: Timestamp;
    serviceCategories: Array<ServiceCategory>;
    averageRating: number;
    longitude: number;
    radiusMiles: bigint;
    completedJobsCount: bigint;
    verificationStatus: VerificationStatus;
}
export type JobId = bigint;
export type EnterpriseDispatchId = bigint;
export interface SubmitRatingInput {
    ratedUserId: UserId;
    jobId: JobId;
    score: bigint;
    comment?: string;
}
export interface RegisterHomeownerInput {
    latitude: number;
    longitude: number;
    address: string;
}
export type UserId = Principal;
export interface RegisterWorkerInput {
    latitude: number;
    idDocRef?: string;
    serviceCategories: Array<ServiceCategory>;
    longitude: number;
    insuranceDocRef?: string;
}
export interface PaymentRecordPublic {
    id: PaymentId;
    tipAmountUSD: bigint;
    createdAt: Timestamp;
    jobId: JobId;
    escrowStatus: EscrowStatus;
    updatedAt: Timestamp;
    commissionAmount: bigint;
    stripePaymentIntentId: string;
    amountUSD: bigint;
    stripePayoutId?: string;
}
export type PaymentId = bigint;
export type NotificationId = bigint;
export interface JobPublic {
    id: JobId;
    status: JobStatus;
    latitude: number;
    completedAt?: Timestamp;
    photoRefs: Array<string>;
    title: string;
    serviceCategory: ServiceCategory;
    workerId?: UserId;
    workerConfirmed: boolean;
    tipAmountUSD?: bigint;
    createdAt: Timestamp;
    homeownerId: UserId;
    description: string;
    longitude: number;
    address: string;
    budgetUSD: bigint;
    acceptedAt?: Timestamp;
    homeownerConfirmed: boolean;
}
export interface HomeownerProfilePublic {
    latitude: number;
    userId: UserId;
    createdAt: Timestamp;
    averageRating: number;
    longitude: number;
    address: string;
}
export type RatingId = bigint;
export interface EnterpriseDispatchPublic {
    id: EnterpriseDispatchId;
    status: EnterpriseDispatchStatus;
    title: string;
    serviceCategory: ServiceCategory;
    createdAt: Timestamp;
    description: string;
    enterpriseClientId: UserId;
    updatedAt: Timestamp;
    workerIds: Array<UserId>;
    address: string;
    budgetUSD: bigint;
}
export interface CreateEnterpriseDispatchInput {
    title: string;
    serviceCategory: ServiceCategory;
    description: string;
    address: string;
    budgetUSD: bigint;
}
export interface NotificationPublic {
    id: NotificationId;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    jobId?: JobId;
    isRead: boolean;
    message: string;
}
export enum EnterpriseDispatchStatus {
    Open = "Open",
    Cancelled = "Cancelled",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum EscrowStatus {
    Refunded = "Refunded",
    Held = "Held",
    Released = "Released"
}
export enum JobStatus {
    Disputed = "Disputed",
    Open = "Open",
    Accepted = "Accepted",
    Cancelled = "Cancelled",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum NotificationType {
    JobAccepted = "JobAccepted",
    EnterpriseDispatch = "EnterpriseDispatch",
    TipReceived = "TipReceived",
    JobCompleted = "JobCompleted",
    JobAvailable = "JobAvailable",
    RatingReceived = "RatingReceived"
}
export enum ServiceCategory {
    BushTrimming = "BushTrimming",
    GeneralYardWork = "GeneralYardWork",
    LeafRaking = "LeafRaking",
    LawnMowing = "LawnMowing",
    WindowWashing = "WindowWashing",
    WeedWhacking = "WeedWhacking",
    SnowPlowing = "SnowPlowing",
    GutterCleaning = "GutterCleaning",
    PressureWashing = "PressureWashing"
}
export enum VerificationStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    acceptJob(id: JobId): Promise<boolean>;
    acceptLiabilityWaiver(version: string): Promise<boolean>;
    addJobTip(id: JobId, tipAmountUSD: bigint): Promise<boolean>;
    addTip(input: AddTipInput): Promise<boolean>;
    assignWorkerToDispatch(dispatchId: EnterpriseDispatchId, workerId: UserId): Promise<boolean>;
    cancelJob(id: JobId): Promise<boolean>;
    createEnterpriseDispatch(input: CreateEnterpriseDispatchInput): Promise<EnterpriseDispatchPublic>;
    createJob(input: CreateJobInput): Promise<JobPublic>;
    disputeJob(id: JobId): Promise<boolean>;
    findNearbyWorkers(lat: number, lng: number, category: ServiceCategory): Promise<Array<WorkerProfilePublic>>;
    getAvailableJobs(): Promise<Array<JobPublic>>;
    getAverageRating(userId: UserId): Promise<number>;
    getEnterpriseDispatch(id: EnterpriseDispatchId): Promise<EnterpriseDispatchPublic | null>;
    getHomeownerProfile(userId: UserId): Promise<HomeownerProfilePublic | null>;
    getJob(id: JobId): Promise<JobPublic | null>;
    getMyEnterpriseDispatches(): Promise<Array<EnterpriseDispatchPublic>>;
    getMyHomeownerProfile(): Promise<HomeownerProfilePublic | null>;
    getMyNotifications(): Promise<Array<NotificationPublic>>;
    getMyPostedJobs(): Promise<Array<JobPublic>>;
    getMyWorkerJobs(): Promise<Array<JobPublic>>;
    getMyWorkerProfile(): Promise<WorkerProfilePublic | null>;
    getOpenEnterpriseDispatches(): Promise<Array<EnterpriseDispatchPublic>>;
    getPaymentForJob(jobId: JobId): Promise<PaymentRecordPublic | null>;
    getRatingsForUser(userId: UserId): Promise<Array<Rating>>;
    getWorkerProfile(userId: UserId): Promise<WorkerProfilePublic | null>;
    hasAcceptedWaiver(): Promise<boolean>;
    homeownerConfirmCompletion(id: JobId): Promise<boolean>;
    initiateEscrow(input: InitiatePaymentInput): Promise<PaymentRecordPublic>;
    markAllNotificationsRead(): Promise<boolean>;
    markNotificationRead(notifId: NotificationId): Promise<boolean>;
    refundEscrow(jobId: JobId): Promise<boolean>;
    registerHomeowner(input: RegisterHomeownerInput): Promise<HomeownerProfilePublic>;
    registerWorker(input: RegisterWorkerInput): Promise<WorkerProfilePublic>;
    releaseEscrow(jobId: JobId, stripePayoutId: string): Promise<boolean>;
    removeWorkerFromDispatch(dispatchId: EnterpriseDispatchId, workerId: UserId): Promise<boolean>;
    startJob(id: JobId): Promise<boolean>;
    submitRating(input: SubmitRatingInput): Promise<Rating>;
    updateEnterpriseDispatchStatus(dispatchId: EnterpriseDispatchId, status: EnterpriseDispatchStatus): Promise<boolean>;
    updateWorkerLocation(latitude: number, longitude: number): Promise<boolean>;
    updateWorkerRadius(newRadius: bigint): Promise<boolean>;
    updateWorkerVerification(workerId: UserId, status: VerificationStatus): Promise<boolean>;
    workerConfirmCompletion(id: JobId): Promise<boolean>;
}
import type { CreateEnterpriseDispatchInput as _CreateEnterpriseDispatchInput, CreateJobInput as _CreateJobInput, EnterpriseDispatchId as _EnterpriseDispatchId, EnterpriseDispatchPublic as _EnterpriseDispatchPublic, EnterpriseDispatchStatus as _EnterpriseDispatchStatus, EscrowStatus as _EscrowStatus, HomeownerProfilePublic as _HomeownerProfilePublic, JobId as _JobId, JobPublic as _JobPublic, JobStatus as _JobStatus, NotificationId as _NotificationId, NotificationPublic as _NotificationPublic, NotificationType as _NotificationType, PaymentId as _PaymentId, PaymentRecordPublic as _PaymentRecordPublic, Rating as _Rating, RatingId as _RatingId, RegisterWorkerInput as _RegisterWorkerInput, ServiceCategory as _ServiceCategory, SubmitRatingInput as _SubmitRatingInput, Timestamp as _Timestamp, UserId as _UserId, VerificationStatus as _VerificationStatus, WorkerProfilePublic as _WorkerProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptJob(arg0);
            return result;
        }
    }
    async acceptLiabilityWaiver(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptLiabilityWaiver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptLiabilityWaiver(arg0);
            return result;
        }
    }
    async addJobTip(arg0: JobId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addJobTip(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJobTip(arg0, arg1);
            return result;
        }
    }
    async addTip(arg0: AddTipInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTip(arg0);
            return result;
        }
    }
    async assignWorkerToDispatch(arg0: EnterpriseDispatchId, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignWorkerToDispatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignWorkerToDispatch(arg0, arg1);
            return result;
        }
    }
    async cancelJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelJob(arg0);
            return result;
        }
    }
    async createEnterpriseDispatch(arg0: CreateEnterpriseDispatchInput): Promise<EnterpriseDispatchPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createEnterpriseDispatch(to_candid_CreateEnterpriseDispatchInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_EnterpriseDispatchPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEnterpriseDispatch(to_candid_CreateEnterpriseDispatchInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_EnterpriseDispatchPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJob(arg0: CreateJobInput): Promise<JobPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_CreateJobInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JobPublic_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_CreateJobInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JobPublic_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async disputeJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.disputeJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disputeJob(arg0);
            return result;
        }
    }
    async findNearbyWorkers(arg0: number, arg1: number, arg2: ServiceCategory): Promise<Array<WorkerProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.findNearbyWorkers(arg0, arg1, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findNearbyWorkers(arg0, arg1, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableJobs(): Promise<Array<JobPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableJobs();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableJobs();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(arg0: UserId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return result;
        }
    }
    async getEnterpriseDispatch(arg0: EnterpriseDispatchId): Promise<EnterpriseDispatchPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnterpriseDispatch(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnterpriseDispatch(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeownerProfile(arg0: UserId): Promise<HomeownerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeownerProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeownerProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: JobId): Promise<JobPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEnterpriseDispatches(): Promise<Array<EnterpriseDispatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnterpriseDispatches();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnterpriseDispatches();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHomeownerProfile(): Promise<HomeownerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHomeownerProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHomeownerProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPostedJobs(): Promise<Array<JobPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPostedJobs();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPostedJobs();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkerJobs(): Promise<Array<JobPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkerJobs();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkerJobs();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkerProfile(): Promise<WorkerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkerProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkerProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenEnterpriseDispatches(): Promise<Array<EnterpriseDispatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenEnterpriseDispatches();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenEnterpriseDispatches();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentForJob(arg0: JobId): Promise<PaymentRecordPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentForJob(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentForJob(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingsForUser(arg0: UserId): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForUser(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForUser(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerProfile(arg0: UserId): Promise<WorkerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAcceptedWaiver(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAcceptedWaiver();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAcceptedWaiver();
            return result;
        }
    }
    async homeownerConfirmCompletion(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.homeownerConfirmCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.homeownerConfirmCompletion(arg0);
            return result;
        }
    }
    async initiateEscrow(arg0: InitiatePaymentInput): Promise<PaymentRecordPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateEscrow(arg0);
                return from_candid_PaymentRecordPublic_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateEscrow(arg0);
            return from_candid_PaymentRecordPublic_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async refundEscrow(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.refundEscrow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refundEscrow(arg0);
            return result;
        }
    }
    async registerHomeowner(arg0: RegisterHomeownerInput): Promise<HomeownerProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerHomeowner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerHomeowner(arg0);
            return result;
        }
    }
    async registerWorker(arg0: RegisterWorkerInput): Promise<WorkerProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWorker(to_candid_RegisterWorkerInput_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_WorkerProfilePublic_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWorker(to_candid_RegisterWorkerInput_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_WorkerProfilePublic_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async releaseEscrow(arg0: JobId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseEscrow(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseEscrow(arg0, arg1);
            return result;
        }
    }
    async removeWorkerFromDispatch(arg0: EnterpriseDispatchId, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkerFromDispatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkerFromDispatch(arg0, arg1);
            return result;
        }
    }
    async startJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startJob(arg0);
            return result;
        }
    }
    async submitRating(arg0: SubmitRatingInput): Promise<Rating> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(to_candid_SubmitRatingInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Rating_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(to_candid_SubmitRatingInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Rating_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEnterpriseDispatchStatus(arg0: EnterpriseDispatchId, arg1: EnterpriseDispatchStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEnterpriseDispatchStatus(arg0, to_candid_EnterpriseDispatchStatus_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEnterpriseDispatchStatus(arg0, to_candid_EnterpriseDispatchStatus_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWorkerLocation(arg0: number, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerLocation(arg0, arg1);
            return result;
        }
    }
    async updateWorkerRadius(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerRadius(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerRadius(arg0);
            return result;
        }
    }
    async updateWorkerVerification(arg0: UserId, arg1: VerificationStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerVerification(arg0, to_candid_VerificationStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerVerification(arg0, to_candid_VerificationStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async workerConfirmCompletion(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.workerConfirmCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.workerConfirmCompletion(arg0);
            return result;
        }
    }
}
function from_candid_EnterpriseDispatchPublic_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnterpriseDispatchPublic): EnterpriseDispatchPublic {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_EnterpriseDispatchStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnterpriseDispatchStatus): EnterpriseDispatchStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_EscrowStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscrowStatus): EscrowStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_JobPublic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPublic): JobPublic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecordPublic_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecordPublic): PaymentRecordPublic {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerProfilePublic_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfilePublic): WorkerProfilePublic {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EnterpriseDispatchPublic]): EnterpriseDispatchPublic | null {
    return value.length === 0 ? null : from_candid_EnterpriseDispatchPublic_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HomeownerProfilePublic]): HomeownerProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobPublic]): JobPublic | null {
    return value.length === 0 ? null : from_candid_JobPublic_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobId]): JobId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerProfilePublic]): WorkerProfilePublic | null {
    return value.length === 0 ? null : from_candid_WorkerProfilePublic_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecordPublic]): PaymentRecordPublic | null {
    return value.length === 0 ? null : from_candid_PaymentRecordPublic_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    latitude: number;
    completedAt: [] | [_Timestamp];
    photoRefs: Array<string>;
    title: string;
    serviceCategory: _ServiceCategory;
    workerId: [] | [_UserId];
    workerConfirmed: boolean;
    tipAmountUSD: [] | [bigint];
    createdAt: _Timestamp;
    homeownerId: _UserId;
    description: string;
    longitude: number;
    address: string;
    budgetUSD: bigint;
    acceptedAt: [] | [_Timestamp];
    homeownerConfirmed: boolean;
}): {
    id: JobId;
    status: JobStatus;
    latitude: number;
    completedAt?: Timestamp;
    photoRefs: Array<string>;
    title: string;
    serviceCategory: ServiceCategory;
    workerId?: UserId;
    workerConfirmed: boolean;
    tipAmountUSD?: bigint;
    createdAt: Timestamp;
    homeownerId: UserId;
    description: string;
    longitude: number;
    address: string;
    budgetUSD: bigint;
    acceptedAt?: Timestamp;
    homeownerConfirmed: boolean;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n15(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        completedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completedAt)),
        photoRefs: value.photoRefs,
        title: value.title,
        serviceCategory: from_candid_ServiceCategory_n9(_uploadFile, _downloadFile, value.serviceCategory),
        workerId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.workerId)),
        workerConfirmed: value.workerConfirmed,
        tipAmountUSD: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.tipAmountUSD)),
        createdAt: value.createdAt,
        homeownerId: value.homeownerId,
        description: value.description,
        longitude: value.longitude,
        address: value.address,
        budgetUSD: value.budgetUSD,
        acceptedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.acceptedAt)),
        homeownerConfirmed: value.homeownerConfirmed
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    enterpriseTier: boolean;
    userId: _UserId;
    createdAt: _Timestamp;
    serviceCategories: Array<_ServiceCategory>;
    averageRating: number;
    longitude: number;
    radiusMiles: bigint;
    completedJobsCount: bigint;
    verificationStatus: _VerificationStatus;
}): {
    latitude: number;
    enterpriseTier: boolean;
    userId: UserId;
    createdAt: Timestamp;
    serviceCategories: Array<ServiceCategory>;
    averageRating: number;
    longitude: number;
    radiusMiles: bigint;
    completedJobsCount: bigint;
    verificationStatus: VerificationStatus;
} {
    return {
        latitude: value.latitude,
        enterpriseTier: value.enterpriseTier,
        userId: value.userId,
        createdAt: value.createdAt,
        serviceCategories: from_candid_vec_n23(_uploadFile, _downloadFile, value.serviceCategories),
        averageRating: value.averageRating,
        longitude: value.longitude,
        radiusMiles: value.radiusMiles,
        completedJobsCount: value.completedJobsCount,
        verificationStatus: from_candid_VerificationStatus_n24(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    jobId: [] | [_JobId];
    isRead: boolean;
    message: string;
}): {
    id: NotificationId;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    jobId?: JobId;
    isRead: boolean;
    message: string;
} {
    return {
        id: value.id,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n34(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        jobId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.jobId)),
        isRead: value.isRead,
        message: value.message
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    tipAmountUSD: bigint;
    createdAt: _Timestamp;
    jobId: _JobId;
    escrowStatus: _EscrowStatus;
    updatedAt: _Timestamp;
    commissionAmount: bigint;
    stripePaymentIntentId: string;
    amountUSD: bigint;
    stripePayoutId: [] | [string];
}): {
    id: PaymentId;
    tipAmountUSD: bigint;
    createdAt: Timestamp;
    jobId: JobId;
    escrowStatus: EscrowStatus;
    updatedAt: Timestamp;
    commissionAmount: bigint;
    stripePaymentIntentId: string;
    amountUSD: bigint;
    stripePayoutId?: string;
} {
    return {
        id: value.id,
        tipAmountUSD: value.tipAmountUSD,
        createdAt: value.createdAt,
        jobId: value.jobId,
        escrowStatus: from_candid_EscrowStatus_n41(_uploadFile, _downloadFile, value.escrowStatus),
        updatedAt: value.updatedAt,
        commissionAmount: value.commissionAmount,
        stripePaymentIntentId: value.stripePaymentIntentId,
        amountUSD: value.amountUSD,
        stripePayoutId: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.stripePayoutId))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RatingId;
    ratedUserId: _UserId;
    createdAt: _Timestamp;
    jobId: _JobId;
    score: bigint;
    ratedByUserId: _UserId;
    comment: [] | [string];
}): {
    id: RatingId;
    ratedUserId: UserId;
    createdAt: Timestamp;
    jobId: JobId;
    score: bigint;
    ratedByUserId: UserId;
    comment?: string;
} {
    return {
        id: value.id,
        ratedUserId: value.ratedUserId,
        createdAt: value.createdAt,
        jobId: value.jobId,
        score: value.score,
        ratedByUserId: value.ratedByUserId,
        comment: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.comment))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EnterpriseDispatchId;
    status: _EnterpriseDispatchStatus;
    title: string;
    serviceCategory: _ServiceCategory;
    createdAt: _Timestamp;
    description: string;
    enterpriseClientId: _UserId;
    updatedAt: _Timestamp;
    workerIds: Array<_UserId>;
    address: string;
    budgetUSD: bigint;
}): {
    id: EnterpriseDispatchId;
    status: EnterpriseDispatchStatus;
    title: string;
    serviceCategory: ServiceCategory;
    createdAt: Timestamp;
    description: string;
    enterpriseClientId: UserId;
    updatedAt: Timestamp;
    workerIds: Array<UserId>;
    address: string;
    budgetUSD: bigint;
} {
    return {
        id: value.id,
        status: from_candid_EnterpriseDispatchStatus_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        serviceCategory: from_candid_ServiceCategory_n9(_uploadFile, _downloadFile, value.serviceCategory),
        createdAt: value.createdAt,
        description: value.description,
        enterpriseClientId: value.enterpriseClientId,
        updatedAt: value.updatedAt,
        workerIds: value.workerIds,
        address: value.address,
        budgetUSD: value.budgetUSD
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BushTrimming: null;
} | {
    GeneralYardWork: null;
} | {
    LeafRaking: null;
} | {
    LawnMowing: null;
} | {
    WindowWashing: null;
} | {
    WeedWhacking: null;
} | {
    SnowPlowing: null;
} | {
    GutterCleaning: null;
} | {
    PressureWashing: null;
}): ServiceCategory {
    return "BushTrimming" in value ? ServiceCategory.BushTrimming : "GeneralYardWork" in value ? ServiceCategory.GeneralYardWork : "LeafRaking" in value ? ServiceCategory.LeafRaking : "LawnMowing" in value ? ServiceCategory.LawnMowing : "WindowWashing" in value ? ServiceCategory.WindowWashing : "WeedWhacking" in value ? ServiceCategory.WeedWhacking : "SnowPlowing" in value ? ServiceCategory.SnowPlowing : "GutterCleaning" in value ? ServiceCategory.GutterCleaning : "PressureWashing" in value ? ServiceCategory.PressureWashing : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Disputed: null;
} | {
    Open: null;
} | {
    Accepted: null;
} | {
    Cancelled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): JobStatus {
    return "Disputed" in value ? JobStatus.Disputed : "Open" in value ? JobStatus.Open : "Accepted" in value ? JobStatus.Accepted : "Cancelled" in value ? JobStatus.Cancelled : "InProgress" in value ? JobStatus.InProgress : "Completed" in value ? JobStatus.Completed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): VerificationStatus {
    return "Approved" in value ? VerificationStatus.Approved : "Rejected" in value ? VerificationStatus.Rejected : "Pending" in value ? VerificationStatus.Pending : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JobAccepted: null;
} | {
    EnterpriseDispatch: null;
} | {
    TipReceived: null;
} | {
    JobCompleted: null;
} | {
    JobAvailable: null;
} | {
    RatingReceived: null;
}): NotificationType {
    return "JobAccepted" in value ? NotificationType.JobAccepted : "EnterpriseDispatch" in value ? NotificationType.EnterpriseDispatch : "TipReceived" in value ? NotificationType.TipReceived : "JobCompleted" in value ? NotificationType.JobCompleted : "JobAvailable" in value ? NotificationType.JobAvailable : "RatingReceived" in value ? NotificationType.RatingReceived : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Refunded: null;
} | {
    Held: null;
} | {
    Released: null;
}): EscrowStatus {
    return "Refunded" in value ? EscrowStatus.Refunded : "Held" in value ? EscrowStatus.Held : "Released" in value ? EscrowStatus.Released : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Cancelled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): EnterpriseDispatchStatus {
    return "Open" in value ? EnterpriseDispatchStatus.Open : "Cancelled" in value ? EnterpriseDispatchStatus.Cancelled : "InProgress" in value ? EnterpriseDispatchStatus.InProgress : "Completed" in value ? EnterpriseDispatchStatus.Completed : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerProfilePublic>): Array<WorkerProfilePublic> {
    return value.map((x)=>from_candid_WorkerProfilePublic_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceCategory>): Array<ServiceCategory> {
    return value.map((x)=>from_candid_ServiceCategory_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPublic>): Array<JobPublic> {
    return value.map((x)=>from_candid_JobPublic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EnterpriseDispatchPublic>): Array<EnterpriseDispatchPublic> {
    return value.map((x)=>from_candid_EnterpriseDispatchPublic_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rating>): Array<Rating> {
    return value.map((x)=>from_candid_Rating_n45(_uploadFile, _downloadFile, x));
}
function to_candid_CreateEnterpriseDispatchInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEnterpriseDispatchInput): _CreateEnterpriseDispatchInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateJobInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobInput): _CreateJobInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_EnterpriseDispatchStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnterpriseDispatchStatus): _EnterpriseDispatchStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterWorkerInput_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterWorkerInput): _RegisterWorkerInput {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitRatingInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitRatingInput): _SubmitRatingInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    photoRefs: Array<string>;
    title: string;
    serviceCategory: ServiceCategory;
    description: string;
    longitude: number;
    address: string;
    budgetUSD: bigint;
}): {
    latitude: number;
    photoRefs: Array<string>;
    title: string;
    serviceCategory: _ServiceCategory;
    description: string;
    longitude: number;
    address: string;
    budgetUSD: bigint;
} {
    return {
        latitude: value.latitude,
        photoRefs: value.photoRefs,
        title: value.title,
        serviceCategory: to_candid_ServiceCategory_n3(_uploadFile, _downloadFile, value.serviceCategory),
        description: value.description,
        longitude: value.longitude,
        address: value.address,
        budgetUSD: value.budgetUSD
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    serviceCategory: ServiceCategory;
    description: string;
    address: string;
    budgetUSD: bigint;
}): {
    title: string;
    serviceCategory: _ServiceCategory;
    description: string;
    address: string;
    budgetUSD: bigint;
} {
    return {
        title: value.title,
        serviceCategory: to_candid_ServiceCategory_n3(_uploadFile, _downloadFile, value.serviceCategory),
        description: value.description,
        address: value.address,
        budgetUSD: value.budgetUSD
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    idDocRef?: string;
    serviceCategories: Array<ServiceCategory>;
    longitude: number;
    insuranceDocRef?: string;
}): {
    latitude: number;
    idDocRef: [] | [string];
    serviceCategories: Array<_ServiceCategory>;
    longitude: number;
    insuranceDocRef: [] | [string];
} {
    return {
        latitude: value.latitude,
        idDocRef: value.idDocRef ? candid_some(value.idDocRef) : candid_none(),
        serviceCategories: to_candid_vec_n49(_uploadFile, _downloadFile, value.serviceCategories),
        longitude: value.longitude,
        insuranceDocRef: value.insuranceDocRef ? candid_some(value.insuranceDocRef) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ratedUserId: UserId;
    jobId: JobId;
    score: bigint;
    comment?: string;
}): {
    ratedUserId: _UserId;
    jobId: _JobId;
    score: bigint;
    comment: [] | [string];
} {
    return {
        ratedUserId: value.ratedUserId,
        jobId: value.jobId,
        score: value.score,
        comment: value.comment ? candid_some(value.comment) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    BushTrimming: null;
} | {
    GeneralYardWork: null;
} | {
    LeafRaking: null;
} | {
    LawnMowing: null;
} | {
    WindowWashing: null;
} | {
    WeedWhacking: null;
} | {
    SnowPlowing: null;
} | {
    GutterCleaning: null;
} | {
    PressureWashing: null;
} {
    return value == ServiceCategory.BushTrimming ? {
        BushTrimming: null
    } : value == ServiceCategory.GeneralYardWork ? {
        GeneralYardWork: null
    } : value == ServiceCategory.LeafRaking ? {
        LeafRaking: null
    } : value == ServiceCategory.LawnMowing ? {
        LawnMowing: null
    } : value == ServiceCategory.WindowWashing ? {
        WindowWashing: null
    } : value == ServiceCategory.WeedWhacking ? {
        WeedWhacking: null
    } : value == ServiceCategory.SnowPlowing ? {
        SnowPlowing: null
    } : value == ServiceCategory.GutterCleaning ? {
        GutterCleaning: null
    } : value == ServiceCategory.PressureWashing ? {
        PressureWashing: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnterpriseDispatchStatus): {
    Open: null;
} | {
    Cancelled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} {
    return value == EnterpriseDispatchStatus.Open ? {
        Open: null
    } : value == EnterpriseDispatchStatus.Cancelled ? {
        Cancelled: null
    } : value == EnterpriseDispatchStatus.InProgress ? {
        InProgress: null
    } : value == EnterpriseDispatchStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == VerificationStatus.Approved ? {
        Approved: null
    } : value == VerificationStatus.Rejected ? {
        Rejected: null
    } : value == VerificationStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ServiceCategory>): Array<_ServiceCategory> {
    return value.map((x)=>to_candid_ServiceCategory_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
